### ISSUE TITLE
Kreisliga Thüringen - Schema fixen

### ISSUE THREAD

**Issue by chris2k2** [chris2k2/ber#34]
https://www.turnier.de/sport/teammatch.aspx?id=6CE96327-26FB-4514-864A-0D5E58FED4D1&match=10

funtkioniert nicht zu parsen

**Comment by chris2k2** [comment]
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `de.cweyermann.ber.matches.entity.Match$Discipline` from String "Kreisliga Nord – Kreisliga Nordthüringen": value not one of declared Enum instance names: [MX, WS, WD, MS, MD]
 at [Source: (String)"[{"league":"","hometeam":null,"awayteam":null,"discipline":"Kreisliga Nord – Kreisliga Nordthüringen","date":"2018-09-02T10:00:00","homePlayers":[],"awayPlayers":[],"result":"","source":"turnierde"},{"league":"","hometeam":null,"awayteam":null,"discipline":"Kreisliga Nord – Kreisliga Nordthüringen","date":"2018-09-02T10:00:00","homePlayers":[],"awayPlayers":[],"result":"","source":"turnierde"},{"league":"","hometeam":null,"awayteam":null,"discipline":"Kreisliga Nord – Kreisliga Nordthüringen","d"[truncated 13757 chars]; line: 1, column: 60] (through reference chain: java.lang.Object[][0]->de.cweyermann.ber.matches.entity.Match["discipline"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1548) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:910) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:255) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:179) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:368) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:195) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[jackson-databind-2.9.3.jar:2.9.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992) ~[jackson-databind-2.9.3.jar:2.9.3]
	at de.cweyermann.ber.matches.boundary.sqs.FilteredMatchesSender.filter(FilteredMatchesSender.java:52) ~[classes/:na]
	at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:181) ~[spring-messaging-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:114) ~[spring-messaging-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:515) ~[spring-messaging-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	... 8 common frames omitted
